### ISSUE TITLE
IntelliSense Fails to Recognize Fields of Object Bound from Reusable Topic Output

### ISSUE THREAD

**Issue by v-mlipari** [microsoft/vscode-copilotstudio#29]
IntelliSense is not recognizing a variable path for fields within an object that was defined as an output of a reusable topic.

**Output Details of reusable Topic**

```
outputType:
  properties:
    GetTransferDestination:
      displayName: GetTransferDestination
      type:
        kind: Record
        properties:
          status: String
          transferNumber: String
```

Global.GetTransferDestination is declared by binding to GetTransferDestination of this redirect topic
```
      dialog: cr729_agent.topic.XR0030_GetTransferDestination_DB
      output:
        binding:
          GetTransferDestination: Global.GetTransferDestination
          status: Topic.status
```

However, IntelliSense does not recognize the fields under the root object Global.GetTransferDestination elsewhere in the code:

 
![Image](https://github.com/user-attachments/assets/489af9bd-ebb0-42f3-9391-559d08d3e308)
